train = read.csv(file = './data/toxic_train.csv',stringsAsFactors = F)
head(train)
names(train)
dim(train)
library(tm)
library(SnowballC)
library(textreg)
library(magrittr)
library(data.table)
library(Cairo)
library(wordcloud)
library(RColorBrewer)
library(tmcn)
corpus = VCorpus(VectorSource(train$comment_text))
corpus = tm_map(corpus, content_transformer(tolower))
corpus = tm_map(corpus, removeNumbers)
corpus = tm_map(corpus, removePunctuation)
corpus = tm_map(corpus, removeWords, stopwords())
corpus = tm_map(corpus, stemDocument)
corpus = tm_map(corpus, stripWhitespace)
dtm = DocumentTermMatrix(corpus)
sparse = removeSparseTerms(dtm, 0.99)
