x <-rnorm(5)
rnorm(5) -> x
demo(graphics)
q()
age = c(1,3,5,2,11,9,3,9,12,3)
age
weight = c(4.4,5.3,7.2,5.2,8.5,7.3,6.0,10.4,10.2,6.1)
weight
mean(weight)
sd(weight)
cor(age,weight)
plot(age,weight)
demo(Hershey)
demo(persp)
demo(image)
he;p.start()
?foo
??foo
'??foo'
example('foo')
RSiteSearch("foo")
apropos("foo", mode="function")
data()
'data(package = .packages(all.available = TRUE))'
vignette()
vignette("foo")
source("filename")
sink("myoutput",append = TRUE,split = FALSE)
sink()
pdf("mygraphs.pdf")
source("file1.R")
source("factors2.R")
.libPaths()
library()
install.packages()
install.packages("vcd")
update.packages()
installed.packages()
library(gclus)
help(package="package_name")
help(package="gclus")
lm(mpg~wt, data=mtcars)
lmfit = lm(mpg~wt, data=mtcars)
lmfit
summary(lmfit)
plot(lmfit)
cook = cooks.distance(lmfit)
cook
plot(cook)
plot()
dev.off()
plot(cars)
predict(lmfit, mynewdata)
help(lm)
help.start()
install.packages("vcd")
help(package="vcd")
 marks2 = c(rep(10,3),rep(20,5),rep(30,2),10,10,rep(40,4),rep(50,4))
 marks2
 length(marks2)
 table(marks2)
 mean(marks2)
 median(marks2)
marks2 = c(rep(10,3),rep(20,5),rep(30,2),rep(10,2),rep(40,4),rep(50,4))
marks2
